version: '3.1'

services:
  go-crud:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:8080"
    networks:
      - internal-net

networks:
  internal-net:
    driver: bridge
    name: database_net
