version: '3.1'

services:
  go-crud:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:8080"
    volumes:
      - .:/go/src/app
    networks:
      - internal-net

networks:
  internal-net:
    driver: bridge
    name: database_docker_net
