name: Docker Compose

on:
  push:
    branches: [ "staging" ]
  pull_request:
    branches: [ "staging" ]

jobs:
  cd:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Deploy Using ssh
      uses: appleboy/ssh-action@staging
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSHKEY }}
        port: ${{ secrets.PORT }}
        script: |
          cd ~/app/go-crud
          git pull origin staging
          git status