name: Docker Compose

on:
  push:
    branches: [ "staging" ]
  pull_request:
    branches: [ "staging" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Copy repository contents via scp
      uses: Baguspanji/go-crud@staging
      env:
        HOST: ${{ DEPLOYMENT.HOST }}
        USERNAME: ${{ DEPLOYMENT.USERNAME }}
        PORT: ${{ DEPLOYMENT.PORT }}
        KEY: ${{ DEPLOYMENT.SSHKEY }}
      with:
        source: "."
        target: "/var/www/mywebsite"

    - name: Executing remote command
      uses: appleboy/ssh-action@master
      with:
        host: ${{ DEPLOYMENT.HOST }}
        USERNAME: ${{ DEPLOYMENT.USERNAME }}
        PORT: ${{ DEPLOYMENT.PORT }}
        KEY: ${{ DEPLOYMENT.SSHKEY }}
        script: ls
